# application.yml
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
#    url: jdbc:postgresql://localhost:5432/resonify
    url: jdbc:postgresql://ep-proud-fog-a1dllgmy-pooler.ap-southeast-1.aws.neon.tech/resonify?user=neondb_owner&password=npg_NXqB4lGAKmo1&sslmode=require&channelBinding=require
#    username: postgres
#    password: changit
    driver-class-name: org.postgresql.Driver

app:
  seed-data: false